# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoogleOS.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import *
import sys
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import importlib


def Google():
    from Apps.browser import MainWindow


def Calendar():
    from Apps.Calendar import MainWindow


def Docs():
    from Apps.Docs import MainWindow


def Drive():
    from Apps.Drive import MainWindow


def Forms():
    from Apps.Forms import MainWindow


def Gmail():
    from Apps.Gmail import MainWindow


def Google_ClassRoom():
    from Apps.Google_Classroom import MainWindow


def Maps():
    from Apps.Google_Maps import MainWindow


def Meet():
    from Apps.Google_Meet import MainWindow


def News():
    from Apps.Google_News import MainWindow


def Sheets():
    from Apps.Sheets import MainWindow


def Slides():
    from Apps.Slides import MainWindow


def Youtube():
    from Apps.Youtube import MainWindow


class Ui_GoogleOS(object):
    def setupUi(self, GoogleOS):
        GoogleOS.setObjectName("GoogleOS")
        GoogleOS.resize(331, 586)
        from PyQt5.QtGui import QIcon
        icon = QIcon()
        icon.addFile(u"../icon.ico", QSize(), QIcon.Normal, QIcon.Off)
        GoogleOS.setWindowIcon(icon)
        GoogleOS.setMinimumSize(QtCore.QSize(331, 586))
        GoogleOS.setMaximumSize(QtCore.QSize(331, 586))
        GoogleOS.setDocumentMode(True)
        GoogleOS.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(GoogleOS)
        self.centralwidget.setObjectName("centralwidget")
        self.Back = QtWidgets.QLabel(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(0, 0, 331, 591))
        self.Back.setText("")
        self.Back.setPixmap(QtGui.QPixmap("back.jpg"))
        self.Back.setObjectName("Back")
        self.App_1 = QtWidgets.QPushButton(self.centralwidget)
        self.App_1.setGeometry(QtCore.QRect(30, 10, 51, 41))
        self.App_1.setStyleSheet("background: transparent;")
        self.App_1.setText("")
        self.App_1.clicked.connect(Google)
        self.App_1.setObjectName("App_1")
        self.App_name_1 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_1.setGeometry(QtCore.QRect(30, 60, 61, 16))
        self.App_name_1.setStyleSheet("color: white;")
        self.App_name_1.setObjectName("App_name_1")
        self.App_logo_1 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_1.setGeometry(QtCore.QRect(40, 20, 21, 21))
        self.App_logo_1.setText("")
        self.App_logo_1.setPixmap(QtGui.QPixmap("App_icon_3.png"))
        self.App_2 = QtWidgets.QPushButton(self.centralwidget)
        self.App_2.setGeometry(QtCore.QRect(90, 10, 51, 41))
        self.App_2.setStyleSheet("background: transparent;")
        self.App_2.setText("")
        self.App_2.setObjectName("App_2")
        self.App_2.clicked.connect(Youtube)
        self.App_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_2.setGeometry(QtCore.QRect(90, 60, 61, 16))
        self.App_name_2.setStyleSheet("color: white;")
        self.App_name_2.setObjectName("App_name_2")
        self.App_logo_2 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_2.setGeometry(QtCore.QRect(100, 20, 21, 21))
        self.App_logo_2.setText("")
        self.App_logo_2.setPixmap(QtGui.QPixmap("App_icon_2.ico"))
        self.App_logo_2.setObjectName("App_logo_2")
        self.App_11 = QtWidgets.QPushButton(self.centralwidget)
        self.App_11.setGeometry(QtCore.QRect(150, 10, 51, 41))
        self.App_11.setStyleSheet("background: transparent;")
        self.App_11.setText("")
        self.App_11.setObjectName("App_11")
        self.App_name_11 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_11.setGeometry(QtCore.QRect(150, 60, 71, 16))
        self.App_name_11.setStyleSheet("color: white;")
        self.App_name_11.setObjectName("App_name_11")
        self.App_logo_11 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_11.setGeometry(QtCore.QRect(160, 20, 21, 21))
        self.App_logo_11.setText("")
        self.App_logo_11.setPixmap(QtGui.QPixmap("App_icon_4.png"))
        self.App_logo_11.setObjectName("App_logo_11")
        self.App_11.clicked.connect(Maps)
        self.App_12 = QtWidgets.QPushButton(self.centralwidget)
        self.App_12.setGeometry(QtCore.QRect(230, 10, 51, 41))
        self.App_12.setStyleSheet("background: transparent;")
        self.App_12.setText("")
        self.App_12.setObjectName("App_12")
        self.App_12.clicked.connect(Calendar)
        self.App_logo_12 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_12.setGeometry(QtCore.QRect(240, 20, 21, 21))
        self.App_logo_12.setText("")
        self.App_logo_12.setPixmap(QtGui.QPixmap("App_icon_5.png"))
        self.App_logo_12.setObjectName("App_logo_12")
        self.App_name_12 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_12.setGeometry(QtCore.QRect(230, 60, 71, 20))
        self.App_name_12.setStyleSheet("color: white;")
        self.App_name_12.setObjectName("App_name_12")
        self.App_name_13 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_13.setGeometry(QtCore.QRect(90, 140, 61, 16))
        self.App_name_13.setStyleSheet("color: white;")
        self.App_name_13.setObjectName("App_name_13")
        self.App_13 = QtWidgets.QPushButton(self.centralwidget)
        self.App_13.setGeometry(QtCore.QRect(150, 90, 51, 41))
        self.App_13.setStyleSheet("background: transparent;")
        self.App_13.setText("")
        self.App_13.clicked.connect(Google_ClassRoom)
        self.App_13.setObjectName("App_13")
        self.App_logo_13 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_13.setGeometry(QtCore.QRect(100, 100, 21, 21))
        self.App_logo_13.setText("")
        self.App_logo_13.setPixmap(QtGui.QPixmap("App_icon_7.png"))
        self.App_logo_13.setObjectName("App_logo_13")
        self.App_logo_14 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_14.setGeometry(QtCore.QRect(240, 100, 21, 21))
        self.App_logo_14.setText("")
        self.App_logo_14.setPixmap(QtGui.QPixmap("App_icon_9.png"))
        self.App_logo_14.setObjectName("App_logo_14")
        self.App_14 = QtWidgets.QPushButton(self.centralwidget)
        self.App_14.setGeometry(QtCore.QRect(30, 90, 51, 41))
        self.App_14.setStyleSheet("background: transparent;")
        self.App_14.setText("")
        self.App_14.setObjectName("App_14")
        self.App_14.clicked.connect(Gmail)
        self.App_name_14 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_14.setGeometry(QtCore.QRect(230, 140, 71, 20))
        self.App_name_14.setStyleSheet("color: white;")
        self.App_name_14.setObjectName("App_name_14")
        self.App_name_15 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_15.setGeometry(QtCore.QRect(30, 140, 61, 16))
        self.App_name_15.setStyleSheet("color: white;")
        self.App_name_15.setObjectName("App_name_15")
        self.App_logo_15 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_15.setGeometry(QtCore.QRect(40, 100, 21, 21))
        self.App_logo_15.setText("")
        self.App_logo_15.setPixmap(QtGui.QPixmap("App_icon_6.png"))
        self.App_logo_15.setObjectName("App_logo_15")
        self.App_15 = QtWidgets.QPushButton(self.centralwidget)
        self.App_15.setGeometry(QtCore.QRect(90, 90, 51, 41))
        self.App_15.setStyleSheet("background: transparent;")
        self.App_15.setText("")
        self.App_15.clicked.connect(Drive)
        self.App_15.setObjectName("App_15")
        self.App_logo_16 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_16.setGeometry(QtCore.QRect(160, 100, 21, 21))
        self.App_logo_16.setText("")
        self.App_logo_16.setPixmap(QtGui.QPixmap("App_icon_8.png"))
        self.App_logo_16.setObjectName("App_logo_16")
        self.App_name_16 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_16.setGeometry(QtCore.QRect(140, 140, 81, 20))
        self.App_name_16.setStyleSheet("color: white;")
        self.App_name_16.setObjectName("App_name_16")
        self.App_16 = QtWidgets.QPushButton(self.centralwidget)
        self.App_16.setGeometry(QtCore.QRect(230, 90, 51, 41))
        self.App_16.setStyleSheet("background: transparent;")
        self.App_16.setText("")
        self.App_16.setObjectName("App_16")
        self.App_16.clicked.connect(Meet)
        self.App_17 = QtWidgets.QPushButton(self.centralwidget)
        self.App_17.setGeometry(QtCore.QRect(230, 180, 51, 41))
        self.App_17.setStyleSheet("background: transparent;")
        self.App_17.setText("")
        self.App_17.clicked.connect(Forms)
        self.App_17.setObjectName("App_17")
        self.App_18 = QtWidgets.QPushButton(self.centralwidget)
        self.App_18.setGeometry(QtCore.QRect(150, 180, 51, 41))
        self.App_18.setStyleSheet("background: transparent;")
        self.App_18.setText("")
        self.App_18.setObjectName("App_18")
        self.App_18.clicked.connect(Slides)
        self.App_name_17 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_17.setGeometry(QtCore.QRect(90, 230, 61, 16))
        self.App_name_17.setStyleSheet("color: white;")
        self.App_name_17.setObjectName("App_name_17")
        self.App_name_18 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_18.setGeometry(QtCore.QRect(150, 230, 71, 16))
        self.App_name_18.setStyleSheet("color: white;")
        self.App_name_18.setObjectName("App_name_18")
        self.App_name_19 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_19.setGeometry(QtCore.QRect(230, 230, 71, 20))
        self.App_name_19.setStyleSheet("color: white;")
        self.App_name_19.setObjectName("App_name_19")
        self.App_logo_17 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_17.setGeometry(QtCore.QRect(160, 190, 21, 21))
        self.App_logo_17.setText("")
        self.App_logo_17.setPixmap(QtGui.QPixmap("App_icon_12.png"))
        self.App_logo_17.setObjectName("App_logo_17")
        self.App_19 = QtWidgets.QPushButton(self.centralwidget)
        self.App_19.setGeometry(QtCore.QRect(90, 180, 51, 41))
        self.App_19.setStyleSheet("background: transparent;")
        self.App_19.setText("")
        self.App_19.setObjectName("App_19")
        self.App_19.clicked.connect(Docs)
        self.App_logo_18 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_18.setGeometry(QtCore.QRect(40, 190, 21, 21))
        self.App_logo_18.setText("")
        self.App_logo_18.setPixmap(QtGui.QPixmap("App_icon_10.png"))
        self.App_logo_18.setObjectName("App_logo_18")
        self.App_logo_19 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_19.setGeometry(QtCore.QRect(100, 190, 21, 21))
        self.App_logo_19.setText("")
        self.App_logo_19.setPixmap(QtGui.QPixmap("App_icon_11.png"))
        self.App_logo_19.setObjectName("App_logo_19")
        self.App_name_20 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_20.setGeometry(QtCore.QRect(20, 230, 61, 20))
        self.App_name_20.setStyleSheet("color: white;")
        self.App_name_20.setObjectName("App_name_20")
        self.App_20 = QtWidgets.QPushButton(self.centralwidget)
        self.App_20.setGeometry(QtCore.QRect(30, 180, 51, 41))
        self.App_20.setStyleSheet("background: transparent;")
        self.App_20.setText("")
        self.App_20.setObjectName("App_20")
        self.App_20.clicked.connect(News)
        self.App_logo_20 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_20.setGeometry(QtCore.QRect(240, 190, 21, 21))
        self.App_logo_20.setText("")
        self.App_logo_20.setPixmap(QtGui.QPixmap("App_icon_13.png"))
        self.App_logo_20.setObjectName("App_logo_20")
        self.App_logo_21 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_21.setGeometry(QtCore.QRect(160, 270, 21, 21))
        self.App_logo_21.setText("")
        self.App_logo_21.setPixmap(QtGui.QPixmap(""))
        self.App_logo_21.setObjectName("App_logo_21")
        self.App_name_21 = QtWidgets.QLabel(self.centralwidget)
        self.App_name_21.setGeometry(QtCore.QRect(30, 310, 61, 16))
        self.App_name_21.setStyleSheet("color: white;")
        self.App_name_21.setObjectName("App_name_21")
        self.App_logo_22 = QtWidgets.QLabel(self.centralwidget)
        self.App_logo_22.setGeometry(QtCore.QRect(40, 270, 21, 21))
        self.App_logo_22.setText("")
        self.App_logo_22.setPixmap(QtGui.QPixmap("App_icon_14.png"))
        self.App_logo_22.setObjectName("App_logo_22")
        GoogleOS.setCentralWidget(self.centralwidget)
        self.retranslateUi(GoogleOS)
        QtCore.QMetaObject.connectSlotsByName(GoogleOS)

    def retranslateUi(self, GoogleOS):
        _translate = QtCore.QCoreApplication.translate
        GoogleOS.setWindowTitle(_translate("GoogleOS", "GoogleOS"))
        self.App_name_1.setText(_translate("GoogleOS", "Google"))
        self.App_name_2.setText(_translate("GoogleOS", "Youtube"))
        self.App_name_11.setText(_translate("GoogleOS", "Google Maps"))
        self.App_name_12.setText(_translate("GoogleOS", "Calendar"))
        self.App_name_13.setText(_translate("GoogleOS", "Drive"))
        self.App_name_14.setText(_translate("GoogleOS", "Google Meet"))
        self.App_name_15.setText(_translate("GoogleOS", "Gmail"))
        self.App_name_16.setText(_translate("GoogleOS", "Google Classroom"))
        self.App_name_17.setText(_translate("GoogleOS", "Docs"))
        self.App_name_18.setText(_translate("GoogleOS", "Slides"))
        self.App_name_19.setText(_translate("GoogleOS", "Forms"))
        self.App_name_20.setText(_translate("GoogleOS", "Google News"))
        self.App_name_21.setText(_translate("GoogleOS", "Sheets"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    GoogleOS = QtWidgets.QMainWindow()
    ui = Ui_GoogleOS()
    ui.setupUi(GoogleOS)
    GoogleOS.show()
    sys.exit(app.exec_())
